import AdjustReadyToPayoutGeneric from '../models/adjust-ready-to-payout-generic';
import { AdjustReadyToPayoutPaymentMethod } from '../models/adjust-ready-to-payout-payment-method';

export default class AdjustReadyToPayoutPaymentMethodFactory {
  static from(data: any = {}): AdjustReadyToPayoutPaymentMethod {
    switch(data.paymentMethod) {
      case 'AdvCash': return new AdjustReadyToPayoutGeneric(data);
      case 'Alfa-click': return new AdjustReadyToPayoutGeneric(data);
      case 'Alipay': return new AdjustReadyToPayoutGeneric(data);
      case 'AstroPay Card': return new AdjustReadyToPayoutGeneric(data);
      case 'AstroPay-GO': return new AdjustReadyToPayoutGeneric(data);
      case 'Baloto': return new AdjustReadyToPayoutGeneric(data);
      case 'Bancontact': return new AdjustReadyToPayoutGeneric(data);
      case 'Bancontact-mobile': return new AdjustReadyToPayoutGeneric(data);
      case 'BankReferenced': return new AdjustReadyToPayoutGeneric(data);
      case 'Beeline': return new AdjustReadyToPayoutGeneric(data);
      case 'Belfius-direct-net': return new AdjustReadyToPayoutGeneric(data);
      case 'Bizum': return new AdjustReadyToPayoutGeneric(data);
      case 'Boleto': return new AdjustReadyToPayoutGeneric(data);
      case 'CASHlib': return new AdjustReadyToPayoutGeneric(data);
      case 'CODVoucher': return new AdjustReadyToPayoutGeneric(data);
      case 'CashToCode': return new AdjustReadyToPayoutGeneric(data);
      case 'China UnionPay': return new AdjustReadyToPayoutGeneric(data);
      case 'Cleo': return new AdjustReadyToPayoutGeneric(data);
      case 'Conekta-oxxo': return new AdjustReadyToPayoutGeneric(data);
      case 'Cupon-de-pagos': return new AdjustReadyToPayoutGeneric(data);
      case 'EPS': return new AdjustReadyToPayoutGeneric(data);
      case 'Efecty': return new AdjustReadyToPayoutGeneric(data);
      case 'FasterPay': return new AdjustReadyToPayoutGeneric(data);
      case 'Flexepin': return new AdjustReadyToPayoutGeneric(data);
      case 'Giropay': return new AdjustReadyToPayoutGeneric(data);
      case 'Google Pay': return new AdjustReadyToPayoutGeneric(data);
      case 'Gpaysafe': return new AdjustReadyToPayoutGeneric(data);
      case 'ING-homepay': return new AdjustReadyToPayoutGeneric(data);
      case 'INOVAPAY-pin': return new AdjustReadyToPayoutGeneric(data);
      case 'INOVAPAY-wallet': return new AdjustReadyToPayoutGeneric(data);
      case 'InstaDebit': return new AdjustReadyToPayoutGeneric(data);
      case 'InstantPayments': return new AdjustReadyToPayoutGeneric(data);
      case 'Interac': return new AdjustReadyToPayoutGeneric(data);
      case 'Interac-eTransfer': return new AdjustReadyToPayoutGeneric(data);
      case 'Interac-online': return new AdjustReadyToPayoutGeneric(data);
      case 'Jeton': return new AdjustReadyToPayoutGeneric(data);
      case 'KNOT': return new AdjustReadyToPayoutGeneric(data);
      case 'Khelocard': return new AdjustReadyToPayoutGeneric(data);
      case 'Klarna': return new AdjustReadyToPayoutGeneric(data);
      case 'MTS': return new AdjustReadyToPayoutGeneric(data);
      case 'Matrix': return new AdjustReadyToPayoutGeneric(data);
      case 'MaxiCash': return new AdjustReadyToPayoutGeneric(data);
      case 'Megafon': return new AdjustReadyToPayoutGeneric(data);
      case 'MiFinity-eWallet': return new AdjustReadyToPayoutGeneric(data);
      case 'MuchBetter': return new AdjustReadyToPayoutGeneric(data);
      case 'Multibanco': return new AdjustReadyToPayoutGeneric(data);
      case 'Neosurf': return new AdjustReadyToPayoutGeneric(data);
      case 'Netbanking': return new AdjustReadyToPayoutGeneric(data);
      case 'Neteller': return new AdjustReadyToPayoutGeneric(data);
      case 'Nordea-Solo': return new AdjustReadyToPayoutGeneric(data);
      case 'OXXO': return new AdjustReadyToPayoutGeneric(data);
      case 'OchaPay': return new AdjustReadyToPayoutGeneric(data);
      case 'Onlineueberweisen': return new AdjustReadyToPayoutGeneric(data);
      case 'P24': return new AdjustReadyToPayoutGeneric(data);
      case 'POLi': return new AdjustReadyToPayoutGeneric(data);
      case 'Pagadito': return new AdjustReadyToPayoutGeneric(data);
      case 'PagoEffectivo': return new AdjustReadyToPayoutGeneric(data);
      case 'Pagsmile-deposit-express': return new AdjustReadyToPayoutGeneric(data);
      case 'Pagsmile-lottery': return new AdjustReadyToPayoutGeneric(data);
      case 'Pay4Fun': return new AdjustReadyToPayoutGeneric(data);
      case 'PayCash': return new AdjustReadyToPayoutGeneric(data);
      case 'PayTabs': return new AdjustReadyToPayoutGeneric(data);
      case 'Payeer': return new AdjustReadyToPayoutGeneric(data);
      case 'PaymentAsia-crypto': return new AdjustReadyToPayoutGeneric(data);
      case 'Paymero': return new AdjustReadyToPayoutGeneric(data);
      case 'Paynote': return new AdjustReadyToPayoutGeneric(data);
      case 'Paysafecard': return new AdjustReadyToPayoutGeneric(data);
      case 'Paysafecash': return new AdjustReadyToPayoutGeneric(data);
      case 'Perfect-money': return new AdjustReadyToPayoutGeneric(data);
      case 'PhonePe': return new AdjustReadyToPayoutGeneric(data);
      case 'Piastrix': return new AdjustReadyToPayoutGeneric(data);
      case 'PinPay': return new AdjustReadyToPayoutGeneric(data);
      case 'PostFinance-card': return new AdjustReadyToPayoutGeneric(data);
      case 'PostFinance-e-finance': return new AdjustReadyToPayoutGeneric(data);
      case 'QIWI': return new AdjustReadyToPayoutGeneric(data);
      case 'QPay': return new AdjustReadyToPayoutGeneric(data);
      case 'QQPay': return new AdjustReadyToPayoutGeneric(data);
      case 'Resurs': return new AdjustReadyToPayoutGeneric(data);
      case 'SEPA': return new AdjustReadyToPayoutGeneric(data);
      case 'SMSVoucher': return new AdjustReadyToPayoutGeneric(data);
      case 'SafetyPay': return new AdjustReadyToPayoutGeneric(data);
      case 'Skrill': return new AdjustReadyToPayoutGeneric(data);
      case 'Skrill Rapid Transfer': return new AdjustReadyToPayoutGeneric(data);
      case 'Sofort': return new AdjustReadyToPayoutGeneric(data);
      case 'SparkPay': return new AdjustReadyToPayoutGeneric(data);
      case 'Tele2': return new AdjustReadyToPayoutGeneric(data);
      case 'Terminaly-RF': return new AdjustReadyToPayoutGeneric(data);
      case 'ToditoCash-card': return new AdjustReadyToPayoutGeneric(data);
      case 'Trustly': return new AdjustReadyToPayoutGeneric(data);
      case 'UPI': return new AdjustReadyToPayoutGeneric(data);
      case 'UPayCard': return new AdjustReadyToPayoutGeneric(data);
      case 'USD-coin': return new AdjustReadyToPayoutGeneric(data);
      case 'VCreditos': return new AdjustReadyToPayoutGeneric(data);
      case 'VenusPoint': return new AdjustReadyToPayoutGeneric(data);
      case 'WeChat Pay': return new AdjustReadyToPayoutGeneric(data);
      case 'Webmoney': return new AdjustReadyToPayoutGeneric(data);
      case 'Webpay': return new AdjustReadyToPayoutGeneric(data);
      case 'Webpay Card': return new AdjustReadyToPayoutGeneric(data);
      case 'Webpay-2': return new AdjustReadyToPayoutGeneric(data);
      case 'XPay-P2P': return new AdjustReadyToPayoutGeneric(data);
      case 'XPay-QR': return new AdjustReadyToPayoutGeneric(data);
      case 'Yandex-money': return new AdjustReadyToPayoutGeneric(data);
      case 'Zimpler': return new AdjustReadyToPayoutGeneric(data);
      case 'Zotapay': return new AdjustReadyToPayoutGeneric(data);
      case 'ach': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-2': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-3': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-4': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-5': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-6': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-7': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-8': return new AdjustReadyToPayoutGeneric(data);
      case 'bank-transfer-9': return new AdjustReadyToPayoutGeneric(data);
      case 'bitcoin': return new AdjustReadyToPayoutGeneric(data);
      case 'cash': return new AdjustReadyToPayoutGeneric(data);
      case 'cash-deposit': return new AdjustReadyToPayoutGeneric(data);
      case 'check': return new AdjustReadyToPayoutGeneric(data);
      case 'cryptocurrency': return new AdjustReadyToPayoutGeneric(data);
      case 'domestic-cards': return new AdjustReadyToPayoutGeneric(data);
      case 'ePay.bg': return new AdjustReadyToPayoutGeneric(data);
      case 'eZeeWallet': return new AdjustReadyToPayoutGeneric(data);
      case 'echeck': return new AdjustReadyToPayoutGeneric(data);
      case 'ecoPayz': return new AdjustReadyToPayoutGeneric(data);
      case 'ecoVoucher': return new AdjustReadyToPayoutGeneric(data);
      case 'iDEAL': return new AdjustReadyToPayoutGeneric(data);
      case 'iDebit': return new AdjustReadyToPayoutGeneric(data);
      case 'iWallet': return new AdjustReadyToPayoutGeneric(data);
      case 'instant-bank-transfer': return new AdjustReadyToPayoutGeneric(data);
      case 'invoice': return new AdjustReadyToPayoutGeneric(data);
      case 'jpay': return new AdjustReadyToPayoutGeneric(data);
      case 'loonie': return new AdjustReadyToPayoutGeneric(data);
      case 'miscellaneous': return new AdjustReadyToPayoutGeneric(data);
      case 'online-bank-transfer': return new AdjustReadyToPayoutGeneric(data);
      case 'oriental-wallet': return new AdjustReadyToPayoutGeneric(data);
      case 'payment-card': return new AdjustReadyToPayoutGeneric(data);
      case 'paypal': return new AdjustReadyToPayoutGeneric(data);
      case 'phone': return new AdjustReadyToPayoutGeneric(data);
      case 'plaid-account': return new AdjustReadyToPayoutGeneric(data);
      case 'rapyd-checkout': return new AdjustReadyToPayoutGeneric(data);
      case 'swift-dbt': return new AdjustReadyToPayoutGeneric(data);
      case 'voucher': return new AdjustReadyToPayoutGeneric(data);
      case 'voucher-2': return new AdjustReadyToPayoutGeneric(data);
      case 'voucher-3': return new AdjustReadyToPayoutGeneric(data);
      case 'voucher-4': return new AdjustReadyToPayoutGeneric(data);
      default: {
        const error = new Error('Unknown discriminator value');
        error.name = 'UnknownDiscriminatorValue';
        throw error;
      }
    };
  }
}
