import AlternativePaymentInstrument from '../models/alternative-payment-instrument';
import CashInstrument from '../models/cash-instrument';
import CheckInstrument from '../models/check-instrument';
import VaultedInstrument from '../models/vaulted-instrument';
import { CustomerDefaultPaymentInstrument } from '../models/customer-default-payment-instrument';

export default class CustomerDefaultPaymentInstrumentFactory {
  static from(data: any = {}): CustomerDefaultPaymentInstrument {
    if (Object.prototype.hasOwnProperty.call(data, 'paymentInstrumentId')) {
      return new VaultedInstrument(data);
    }
    switch(data.method) {
      case 'AdvCash': return new AlternativePaymentInstrument(data);
      case 'Aircash': return new AlternativePaymentInstrument(data);
      case 'Airpay': return new AlternativePaymentInstrument(data);
      case 'Alfa-click': return new AlternativePaymentInstrument(data);
      case 'Alipay': return new AlternativePaymentInstrument(data);
      case 'AmazonPay': return new AlternativePaymentInstrument(data);
      case 'Apple Pay': return new AlternativePaymentInstrument(data);
      case 'AstroPay Card': return new AlternativePaymentInstrument(data);
      case 'AstroPay-GO': return new AlternativePaymentInstrument(data);
      case 'Baloto': return new AlternativePaymentInstrument(data);
      case 'Bancontact': return new AlternativePaymentInstrument(data);
      case 'Bancontact-mobile': return new AlternativePaymentInstrument(data);
      case 'BankReferenced': return new AlternativePaymentInstrument(data);
      case 'BankSEND': return new AlternativePaymentInstrument(data);
      case 'Beeline': return new AlternativePaymentInstrument(data);
      case 'Belfius-direct-net': return new AlternativePaymentInstrument(data);
      case 'Bizum': return new AlternativePaymentInstrument(data);
      case 'Blik': return new AlternativePaymentInstrument(data);
      case 'Boleto': return new AlternativePaymentInstrument(data);
      case 'Boleto-2': return new AlternativePaymentInstrument(data);
      case 'Boleto-3': return new AlternativePaymentInstrument(data);
      case 'CASHlib': return new AlternativePaymentInstrument(data);
      case 'CCAvenue': return new AlternativePaymentInstrument(data);
      case 'CODVoucher': return new AlternativePaymentInstrument(data);
      case 'CashToCode': return new AlternativePaymentInstrument(data);
      case 'China UnionPay': return new AlternativePaymentInstrument(data);
      case 'Cleo': return new AlternativePaymentInstrument(data);
      case 'Conekta-oxxo': return new AlternativePaymentInstrument(data);
      case 'Conekta-spei': return new AlternativePaymentInstrument(data);
      case 'Cupon-de-pagos': return new AlternativePaymentInstrument(data);
      case 'CyberSource': return new AlternativePaymentInstrument(data);
      case 'Dimoco-pay-smart': return new AlternativePaymentInstrument(data);
      case 'Directa24Card': return new AlternativePaymentInstrument(data);
      case 'EPS': return new AlternativePaymentInstrument(data);
      case 'Efecty': return new AlternativePaymentInstrument(data);
      case 'Ethereum': return new AlternativePaymentInstrument(data);
      case 'FasterPay': return new AlternativePaymentInstrument(data);
      case 'Flexepin': return new AlternativePaymentInstrument(data);
      case 'Giropay': return new AlternativePaymentInstrument(data);
      case 'Google Pay': return new AlternativePaymentInstrument(data);
      case 'Gpaysafe': return new AlternativePaymentInstrument(data);
      case 'ING-homepay': return new AlternativePaymentInstrument(data);
      case 'INOVAPAY-pin': return new AlternativePaymentInstrument(data);
      case 'INOVAPAY-wallet': return new AlternativePaymentInstrument(data);
      case 'InstaDebit': return new AlternativePaymentInstrument(data);
      case 'InstantPayments': return new AlternativePaymentInstrument(data);
      case 'Interac': return new AlternativePaymentInstrument(data);
      case 'Interac-eTransfer': return new AlternativePaymentInstrument(data);
      case 'Interac-express-connect': return new AlternativePaymentInstrument(data);
      case 'Interac-online': return new AlternativePaymentInstrument(data);
      case 'Jeton': return new AlternativePaymentInstrument(data);
      case 'JetonCash': return new AlternativePaymentInstrument(data);
      case 'KNOT': return new AlternativePaymentInstrument(data);
      case 'KakaoPay': return new AlternativePaymentInstrument(data);
      case 'Khelocard': return new AlternativePaymentInstrument(data);
      case 'Klarna': return new AlternativePaymentInstrument(data);
      case 'LPG-online': return new AlternativePaymentInstrument(data);
      case 'LPG-payment-card': return new AlternativePaymentInstrument(data);
      case 'Litecoin': return new AlternativePaymentInstrument(data);
      case 'MTS': return new AlternativePaymentInstrument(data);
      case 'Matrix': return new AlternativePaymentInstrument(data);
      case 'MaxiCash': return new AlternativePaymentInstrument(data);
      case 'Megafon': return new AlternativePaymentInstrument(data);
      case 'MercadoPago': return new AlternativePaymentInstrument(data);
      case 'MiFinity-eWallet': return new AlternativePaymentInstrument(data);
      case 'MobilePay': return new AlternativePaymentInstrument(data);
      case 'MuchBetter': return new AlternativePaymentInstrument(data);
      case 'Multibanco': return new AlternativePaymentInstrument(data);
      case 'MyFatoorah': return new AlternativePaymentInstrument(data);
      case 'Neosurf': return new AlternativePaymentInstrument(data);
      case 'Netbanking': return new AlternativePaymentInstrument(data);
      case 'Neteller': return new AlternativePaymentInstrument(data);
      case 'Nordea-Solo': return new AlternativePaymentInstrument(data);
      case 'NordikCoin': return new AlternativePaymentInstrument(data);
      case 'OXXO': return new AlternativePaymentInstrument(data);
      case 'OchaPay': return new AlternativePaymentInstrument(data);
      case 'Onlineueberweisen': return new AlternativePaymentInstrument(data);
      case 'P24': return new AlternativePaymentInstrument(data);
      case 'PIX': return new AlternativePaymentInstrument(data);
      case 'POLi': return new AlternativePaymentInstrument(data);
      case 'Pagadito': return new AlternativePaymentInstrument(data);
      case 'PagoEffectivo': return new AlternativePaymentInstrument(data);
      case 'Pagsmile-deposit-express': return new AlternativePaymentInstrument(data);
      case 'Pagsmile-lottery': return new AlternativePaymentInstrument(data);
      case 'Pay4Fun': return new AlternativePaymentInstrument(data);
      case 'PayCash': return new AlternativePaymentInstrument(data);
      case 'PayTabs': return new AlternativePaymentInstrument(data);
      case 'PayU': return new AlternativePaymentInstrument(data);
      case 'PayULatam': return new AlternativePaymentInstrument(data);
      case 'Payco': return new AlternativePaymentInstrument(data);
      case 'Payeer': return new AlternativePaymentInstrument(data);
      case 'PaymentAsia-crypto': return new AlternativePaymentInstrument(data);
      case 'Paymero': return new AlternativePaymentInstrument(data);
      case 'Paymero-QR': return new AlternativePaymentInstrument(data);
      case 'Paynote': return new AlternativePaymentInstrument(data);
      case 'Paysafecard': return new AlternativePaymentInstrument(data);
      case 'Perfect-money': return new AlternativePaymentInstrument(data);
      case 'PhonePe': return new AlternativePaymentInstrument(data);
      case 'Piastrix': return new AlternativePaymentInstrument(data);
      case 'PinPay': return new AlternativePaymentInstrument(data);
      case 'PostFinance-card': return new AlternativePaymentInstrument(data);
      case 'PostFinance-e-finance': return new AlternativePaymentInstrument(data);
      case 'QIWI': return new AlternativePaymentInstrument(data);
      case 'QPay': return new AlternativePaymentInstrument(data);
      case 'QQPay': return new AlternativePaymentInstrument(data);
      case 'Resurs': return new AlternativePaymentInstrument(data);
      case 'SEPA': return new AlternativePaymentInstrument(data);
      case 'SMSVoucher': return new AlternativePaymentInstrument(data);
      case 'SPEI': return new AlternativePaymentInstrument(data);
      case 'SafetyPay': return new AlternativePaymentInstrument(data);
      case 'Samsung Pay': return new AlternativePaymentInstrument(data);
      case 'Siirto': return new AlternativePaymentInstrument(data);
      case 'Skrill': return new AlternativePaymentInstrument(data);
      case 'Skrill Rapid Transfer': return new AlternativePaymentInstrument(data);
      case 'Sofort': return new AlternativePaymentInstrument(data);
      case 'SparkPay': return new AlternativePaymentInstrument(data);
      case 'TWINT': return new AlternativePaymentInstrument(data);
      case 'Tele2': return new AlternativePaymentInstrument(data);
      case 'Telr': return new AlternativePaymentInstrument(data);
      case 'Terminaly-RF': return new AlternativePaymentInstrument(data);
      case 'Tether': return new AlternativePaymentInstrument(data);
      case 'ToditoCash-card': return new AlternativePaymentInstrument(data);
      case 'Trustly': return new AlternativePaymentInstrument(data);
      case 'Tupay': return new AlternativePaymentInstrument(data);
      case 'UPI': return new AlternativePaymentInstrument(data);
      case 'UPayCard': return new AlternativePaymentInstrument(data);
      case 'USD-coin': return new AlternativePaymentInstrument(data);
      case 'UniCrypt': return new AlternativePaymentInstrument(data);
      case 'VCreditos': return new AlternativePaymentInstrument(data);
      case 'VegaWallet': return new AlternativePaymentInstrument(data);
      case 'VenusPoint': return new AlternativePaymentInstrument(data);
      case 'Wallet88': return new AlternativePaymentInstrument(data);
      case 'WeChat Pay': return new AlternativePaymentInstrument(data);
      case 'Webmoney': return new AlternativePaymentInstrument(data);
      case 'Webpay': return new AlternativePaymentInstrument(data);
      case 'Webpay Card': return new AlternativePaymentInstrument(data);
      case 'Webpay-2': return new AlternativePaymentInstrument(data);
      case 'XPay-P2P': return new AlternativePaymentInstrument(data);
      case 'XPay-QR': return new AlternativePaymentInstrument(data);
      case 'Yandex-money': return new AlternativePaymentInstrument(data);
      case 'Zimpler': return new AlternativePaymentInstrument(data);
      case 'Zotapay': return new AlternativePaymentInstrument(data);
      case 'ach': return new AlternativePaymentInstrument(data);
      case 'bank-transfer': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-2': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-3': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-4': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-5': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-6': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-7': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-8': return new AlternativePaymentInstrument(data);
      case 'bank-transfer-9': return new AlternativePaymentInstrument(data);
      case 'bitcoin': return new AlternativePaymentInstrument(data);
      case 'cash-deposit': return new AlternativePaymentInstrument(data);
      case 'cryptocurrency': return new AlternativePaymentInstrument(data);
      case 'domestic-cards': return new AlternativePaymentInstrument(data);
      case 'e-wallet': return new AlternativePaymentInstrument(data);
      case 'ePay.bg': return new AlternativePaymentInstrument(data);
      case 'eZeeWallet': return new AlternativePaymentInstrument(data);
      case 'echeck': return new AlternativePaymentInstrument(data);
      case 'ecoPayz': return new AlternativePaymentInstrument(data);
      case 'ecoVoucher': return new AlternativePaymentInstrument(data);
      case 'ezyEFT': return new AlternativePaymentInstrument(data);
      case 'iDEAL': return new AlternativePaymentInstrument(data);
      case 'iDebit': return new AlternativePaymentInstrument(data);
      case 'iWallet': return new AlternativePaymentInstrument(data);
      case 'instant-bank-transfer': return new AlternativePaymentInstrument(data);
      case 'invoice': return new AlternativePaymentInstrument(data);
      case 'jpay': return new AlternativePaymentInstrument(data);
      case 'loonie': return new AlternativePaymentInstrument(data);
      case 'miscellaneous': return new AlternativePaymentInstrument(data);
      case 'online-bank-transfer': return new AlternativePaymentInstrument(data);
      case 'oriental-wallet': return new AlternativePaymentInstrument(data);
      case 'payment-card': return new AlternativePaymentInstrument(data);
      case 'paypal': return new AlternativePaymentInstrument(data);
      case 'phone': return new AlternativePaymentInstrument(data);
      case 'rapyd-checkout': return new AlternativePaymentInstrument(data);
      case 'rebilly-hosted-payment-form': return new AlternativePaymentInstrument(data);
      case 'swift-dbt': return new AlternativePaymentInstrument(data);
      case 'voucher': return new AlternativePaymentInstrument(data);
      case 'voucher-2': return new AlternativePaymentInstrument(data);
      case 'voucher-3': return new AlternativePaymentInstrument(data);
      case 'voucher-4': return new AlternativePaymentInstrument(data);
      case 'cash': return new CashInstrument(data);
      case 'check': return new CheckInstrument(data);
      default: {
        const error = new Error('Unknown discriminator value');
        error.name = 'UnknownDiscriminatorValue';
        throw error;
      }
    };
  }
}
