import A1Gateway from '../models/a-1-gateway';
import ACI from '../models/aci';
import Adyen from '../models/adyen';
import Aircash from '../models/aircash';
import Airpay from '../models/airpay';
import Airwallex from '../models/airwallex';
import AmazonPay from '../models/amazon-pay';
import AmexVPC from '../models/amex-vpc';
import ApcoPay from '../models/apco-pay';
import AsiaPaymentGateway from '../models/asia-payment-gateway';
import AstroPayCard from '../models/astro-pay-card';
import AuthorizeNet from '../models/authorize-net';
import Awepay from '../models/awepay';
import Bambora from '../models/bambora';
import BankSEND from '../models/bank-send';
import BitPay from '../models/bit-pay';
import BlueSnap from '../models/blue-snap';
import BraintreePayments from '../models/braintree-payments';
import Buckaroo from '../models/buckaroo';
import BVNK from '../models/bvnk';
import Cardknox from '../models/cardknox';
import Cashflows from '../models/cashflows';
import CASHlib from '../models/cas-hlib';
import Cashterminal from '../models/cashterminal';
import CashToCode from '../models/cash-to-code';
import CauriPayment from '../models/cauri-payment';
import Cayan from '../models/cayan';
import CCAvenue from '../models/cc-avenue';
import Chase from '../models/chase';
import CheckoutCom from '../models/checkout-com';
import Chillstock from '../models/chillstock';
import Circle from '../models/circle';
import Citadel from '../models/citadel';
import Clearhaus from '../models/clearhaus';
import Cleo from '../models/cleo';
import CODVoucher from '../models/cod-voucher';
import Coinbase from '../models/coinbase';
import CoinGate from '../models/coin-gate';
import CoinPayments from '../models/coin-payments';
import Conekta from '../models/conekta';
import Coppr from '../models/coppr';
import Credorax from '../models/credorax';
import Cryptonator from '../models/cryptonator';
import CyberSource from '../models/cyber-source';
import DataCash from '../models/data-cash';
import Dengi from '../models/dengi';
import Dimoco from '../models/dimoco';
import Directa24 from '../models/directa-24';
import DLocal from '../models/d-local';
import Dragonphoenix from '../models/dragonphoenix';
import Dropayment from '../models/dropayment';
import EasyPayDirect from '../models/easy-pay-direct';
import EBANX from '../models/ebanx';
import EcoPayz from '../models/eco-payz';
import EcorePay from '../models/ecore-pay';
import Elavon from '../models/elavon';
import EMerchantPay from '../models/e-merchant-pay';
import EMS from '../models/ems';
import EPay from '../models/e-pay';
import EPG from '../models/epg';
import EPro from '../models/e-pro';
import Euteller from '../models/euteller';
import Ezeebill from '../models/ezeebill';
import EZeeWallet from '../models/e-zee-wallet';
import EzyEFT from '../models/ezy-eft';
import Finrax from '../models/finrax';
import FinTecSystems from '../models/fin-tec-systems';
import Flexepin from '../models/flexepin';
import Forte from '../models/forte';
import FundSend from '../models/fund-send';
import Gate2way from '../models/gate-2-way';
import GET from '../models/get';
import Gigadat from '../models/gigadat';
import GlobalOne from '../models/global-one';
import Gooney from '../models/gooney';
import Gpaysafe from '../models/gpaysafe';
import Greenbox from '../models/greenbox';
import HiPay from '../models/hi-pay';
import ICanPay from '../models/i-can-pay';
import ICEPAY from '../models/icepay';
import ICheque from '../models/i-cheque';
import IDebit from '../models/i-debit';
import Ilixium from '../models/ilixium';
import Ingenico from '../models/ingenico';
import INOVAPAY from '../models/inovapay';
import Inovio from '../models/inovio';
import InstaDebit from '../models/insta-debit';
import Intuit from '../models/intuit';
import IpayOptions from '../models/ipay-options';
import Jeton from '../models/jeton';
import JetPay from '../models/jet-pay';
import JPMOrbital from '../models/jpm-orbital';
import Khelocard from '../models/khelocard';
import Klarna from '../models/klarna';
import Konnektive from '../models/konnektive';
import LaCore from '../models/la-core';
import Limepay from '../models/limepay';
import Loonie from '../models/loonie';
import LPG from '../models/lpg';
import MaxiCash from '../models/maxi-cash';
import MercadoPago from '../models/mercado-pago';
import MiFinity from '../models/mi-finity';
import MobilePay from '../models/mobile-pay';
import Moneris from '../models/moneris';
import Monolo from '../models/monolo';
import MtaPay from '../models/mta-pay';
import MuchBetter from '../models/much-better';
import MuchBetterGateway from '../models/much-better-gateway';
import MyFatoorah from '../models/my-fatoorah';
import Neosurf from '../models/neosurf';
import Netbanking from '../models/netbanking';
import Neteller from '../models/neteller';
import NGenius from '../models/n-genius';
import NinjaWallet from '../models/ninja-wallet';
import NMI from '../models/nmi';
import NordikCoin from '../models/nordik-coin';
import NOWPayments from '../models/now-payments';
import NuaPay from '../models/nua-pay';
import OchaPay from '../models/ocha-pay';
import OmniMatrix from '../models/omni-matrix';
import Onlineueberweisen from '../models/onlineueberweisen';
import OnRamp from '../models/on-ramp';
import Orbital from '../models/orbital';
import Pagadito from '../models/pagadito';
import Pagsmile from '../models/pagsmile';
import Panamerican from '../models/panamerican';
import PandaGateway from '../models/panda-gateway';
import ParamountCommerce from '../models/paramount-commerce';
import ParamountEft from '../models/paramount-eft';
import ParamountInterac from '../models/paramount-interac';
import Pay4Fun from '../models/pay-4-fun';
import PayCash from '../models/pay-cash';
import PayClub from '../models/pay-club';
import PayCom from '../models/pay-com';
import PayEcards from '../models/pay-ecards';
import Payeezy from '../models/payeezy';
import Payflow from '../models/payflow';
import PaymentAsia from '../models/payment-asia';
import PaymenTechnologies from '../models/paymen-technologies';
import PaymentsOS from '../models/payments-os';
import Paymero from '../models/paymero';
import Paynote from '../models/paynote';
import PayPal from '../models/pay-pal';
import Payper from '../models/payper';
import Payr from '../models/payr';
import PayRedeem from '../models/pay-redeem';
import PayRetailers from '../models/pay-retailers';
import Paysafe from '../models/paysafe';
import Paysafecard from '../models/paysafecard';
import Paysafecash from '../models/paysafecash';
import PayTabs from '../models/pay-tabs';
import PayU from '../models/pay-u';
import PayULatam from '../models/pay-u-latam';
import Payvision from '../models/payvision';
import PharosPayments from '../models/pharos-payments';
import Piastrix from '../models/piastrix';
import Pin4Pay from '../models/pin-4-pay';
import Plugnpay from '../models/plugnpay';
import PostFinance from '../models/post-finance';
import PPRO from '../models/ppro';
import Prosa from '../models/prosa';
import PSiGate from '../models/p-si-gate';
import Rapyd from '../models/rapyd';
import Realex from '../models/realex';
import Realtime from '../models/realtime';
import Redsys from '../models/redsys';
import Rotessa from '../models/rotessa';
import RPN from '../models/rpn';
import Safecharge from '../models/safecharge';
import Sagepay from '../models/sagepay';
import SaltarPay from '../models/saltar-pay';
import SeamlessChex from '../models/seamless-chex';
import SecureTrading from '../models/secure-trading';
import SecurionPay from '../models/securion-pay';
import Skrill from '../models/skrill';
import SmartInvoice from '../models/smart-invoice';
import SMSVoucher from '../models/sms-voucher';
import Sofort from '../models/sofort';
import SparkPay from '../models/spark-pay';
import StaticGateway from '../models/static-gateway';
import STPMexico from '../models/stp-mexico';
import Stripe from '../models/stripe';
import Tabby from '../models/tabby';
import Telr from '../models/telr';
import TestProcessor from '../models/test-processor';
import ToditoCash from '../models/todito-cash';
import Truevo from '../models/truevo';
import Trustly from '../models/trustly';
import TrustsPay from '../models/trusts-pay';
import TWINT from '../models/twint';
import Unlimit from '../models/unlimit';
import UPayCard from '../models/u-pay-card';
import USAePay from '../models/us-ae-pay';
import VantivLitle from '../models/vantiv-litle';
import VCreditos from '../models/v-creditos';
import VegaaH from '../models/vegaa-h';
import VegaWallet from '../models/vega-wallet';
import Wallet88 from '../models/wallet-88';
import Walpay from '../models/walpay';
import WesternUnion from '../models/western-union';
import Wirecard from '../models/wirecard';
import WorldlineAtosFrankfurt from '../models/worldline-atos-frankfurt';
import Worldpay from '../models/worldpay';
import XPay from '../models/x-pay';
import Zimpler from '../models/zimpler';
import Zotapay from '../models/zotapay';
import DigitalWallets from '../models/digital-wallets';
import ResourceLink from '../models/resource-link';
import GatewayAccount from '../models/gateway-account';

export default class GatewayAccountFactory {
  static from(data: any = {}): GatewayAccount {
    switch(data.gatewayName) {
      case 'A1Gateway': return new A1Gateway(data);
      case 'ACI': return new ACI(data);
      case 'Adyen': return new Adyen(data);
      case 'Aircash': return new Aircash(data);
      case 'Airpay': return new Airpay(data);
      case 'Airwallex': return new Airwallex(data);
      case 'AmazonPay': return new AmazonPay(data);
      case 'AmexVPC': return new AmexVPC(data);
      case 'ApcoPay': return new ApcoPay(data);
      case 'AsiaPaymentGateway': return new AsiaPaymentGateway(data);
      case 'AstroPayCard': return new AstroPayCard(data);
      case 'AuthorizeNet': return new AuthorizeNet(data);
      case 'Awepay': return new Awepay(data);
      case 'Bambora': return new Bambora(data);
      case 'BankSEND': return new BankSEND(data);
      case 'BitPay': return new BitPay(data);
      case 'BlueSnap': return new BlueSnap(data);
      case 'BraintreePayments': return new BraintreePayments(data);
      case 'Buckaroo': return new Buckaroo(data);
      case 'BVNK': return new BVNK(data);
      case 'Cardknox': return new Cardknox(data);
      case 'Cashflows': return new Cashflows(data);
      case 'CASHlib': return new CASHlib(data);
      case 'Cashterminal': return new Cashterminal(data);
      case 'CashToCode': return new CashToCode(data);
      case 'CauriPayment': return new CauriPayment(data);
      case 'Cayan': return new Cayan(data);
      case 'CCAvenue': return new CCAvenue(data);
      case 'Chase': return new Chase(data);
      case 'CheckoutCom': return new CheckoutCom(data);
      case 'Chillstock': return new Chillstock(data);
      case 'Circle': return new Circle(data);
      case 'Citadel': return new Citadel(data);
      case 'Clearhaus': return new Clearhaus(data);
      case 'Cleo': return new Cleo(data);
      case 'CODVoucher': return new CODVoucher(data);
      case 'Coinbase': return new Coinbase(data);
      case 'CoinGate': return new CoinGate(data);
      case 'CoinPayments': return new CoinPayments(data);
      case 'Conekta': return new Conekta(data);
      case 'Coppr': return new Coppr(data);
      case 'Credorax': return new Credorax(data);
      case 'Cryptonator': return new Cryptonator(data);
      case 'CyberSource': return new CyberSource(data);
      case 'DataCash': return new DataCash(data);
      case 'Dengi': return new Dengi(data);
      case 'Dimoco': return new Dimoco(data);
      case 'Directa24': return new Directa24(data);
      case 'dLocal': return new DLocal(data);
      case 'Dragonphoenix': return new Dragonphoenix(data);
      case 'Dropayment': return new Dropayment(data);
      case 'EasyPayDirect': return new EasyPayDirect(data);
      case 'EBANX': return new EBANX(data);
      case 'ecoPayz': return new EcoPayz(data);
      case 'EcorePay': return new EcorePay(data);
      case 'Elavon': return new Elavon(data);
      case 'eMerchantPay': return new EMerchantPay(data);
      case 'EMS': return new EMS(data);
      case 'ePay': return new EPay(data);
      case 'EPG': return new EPG(data);
      case 'EPro': return new EPro(data);
      case 'Euteller': return new Euteller(data);
      case 'Ezeebill': return new Ezeebill(data);
      case 'eZeeWallet': return new EZeeWallet(data);
      case 'ezyEFT': return new EzyEFT(data);
      case 'Finrax': return new Finrax(data);
      case 'FinTecSystems': return new FinTecSystems(data);
      case 'Flexepin': return new Flexepin(data);
      case 'Forte': return new Forte(data);
      case 'FundSend': return new FundSend(data);
      case 'gate2way': return new Gate2way(data);
      case 'GET': return new GET(data);
      case 'Gigadat': return new Gigadat(data);
      case 'GlobalOne': return new GlobalOne(data);
      case 'Gooney': return new Gooney(data);
      case 'Gpaysafe': return new Gpaysafe(data);
      case 'Greenbox': return new Greenbox(data);
      case 'HiPay': return new HiPay(data);
      case 'iCanPay': return new ICanPay(data);
      case 'ICEPAY': return new ICEPAY(data);
      case 'iCheque': return new ICheque(data);
      case 'iDebit': return new IDebit(data);
      case 'Ilixium': return new Ilixium(data);
      case 'Ingenico': return new Ingenico(data);
      case 'INOVAPAY': return new INOVAPAY(data);
      case 'Inovio': return new Inovio(data);
      case 'InstaDebit': return new InstaDebit(data);
      case 'Intuit': return new Intuit(data);
      case 'IpayOptions': return new IpayOptions(data);
      case 'Jeton': return new Jeton(data);
      case 'JetPay': return new JetPay(data);
      case 'JPMOrbital': return new JPMOrbital(data);
      case 'Khelocard': return new Khelocard(data);
      case 'Klarna': return new Klarna(data);
      case 'Konnektive': return new Konnektive(data);
      case 'LaCore': return new LaCore(data);
      case 'Limepay': return new Limepay(data);
      case 'loonie': return new Loonie(data);
      case 'LPG': return new LPG(data);
      case 'MaxiCash': return new MaxiCash(data);
      case 'MercadoPago': return new MercadoPago(data);
      case 'MiFinity': return new MiFinity(data);
      case 'MobilePay': return new MobilePay(data);
      case 'Moneris': return new Moneris(data);
      case 'Monolo': return new Monolo(data);
      case 'MtaPay': return new MtaPay(data);
      case 'MuchBetter': return new MuchBetter(data);
      case 'MuchBetterGateway': return new MuchBetterGateway(data);
      case 'MyFatoorah': return new MyFatoorah(data);
      case 'Neosurf': return new Neosurf(data);
      case 'Netbanking': return new Netbanking(data);
      case 'Neteller': return new Neteller(data);
      case 'NGenius': return new NGenius(data);
      case 'NinjaWallet': return new NinjaWallet(data);
      case 'NMI': return new NMI(data);
      case 'NordikCoin': return new NordikCoin(data);
      case 'NOWPayments': return new NOWPayments(data);
      case 'NuaPay': return new NuaPay(data);
      case 'OchaPay': return new OchaPay(data);
      case 'OmniMatrix': return new OmniMatrix(data);
      case 'Onlineueberweisen': return new Onlineueberweisen(data);
      case 'OnRamp': return new OnRamp(data);
      case 'Orbital': return new Orbital(data);
      case 'Pagadito': return new Pagadito(data);
      case 'Pagsmile': return new Pagsmile(data);
      case 'Panamerican': return new Panamerican(data);
      case 'PandaGateway': return new PandaGateway(data);
      case 'ParamountCommerce': return new ParamountCommerce(data);
      case 'ParamountEft': return new ParamountEft(data);
      case 'ParamountInterac': return new ParamountInterac(data);
      case 'Pay4Fun': return new Pay4Fun(data);
      case 'PayCash': return new PayCash(data);
      case 'PayClub': return new PayClub(data);
      case 'PayCom': return new PayCom(data);
      case 'PayEcards': return new PayEcards(data);
      case 'Payeezy': return new Payeezy(data);
      case 'Payflow': return new Payflow(data);
      case 'PaymentAsia': return new PaymentAsia(data);
      case 'PaymenTechnologies': return new PaymenTechnologies(data);
      case 'PaymentsOS': return new PaymentsOS(data);
      case 'Paymero': return new Paymero(data);
      case 'Paynote': return new Paynote(data);
      case 'PayPal': return new PayPal(data);
      case 'Payper': return new Payper(data);
      case 'Payr': return new Payr(data);
      case 'PayRedeem': return new PayRedeem(data);
      case 'PayRetailers': return new PayRetailers(data);
      case 'Paysafe': return new Paysafe(data);
      case 'Paysafecard': return new Paysafecard(data);
      case 'Paysafecash': return new Paysafecash(data);
      case 'PayTabs': return new PayTabs(data);
      case 'PayU': return new PayU(data);
      case 'PayULatam': return new PayULatam(data);
      case 'Payvision': return new Payvision(data);
      case 'PharosPayments': return new PharosPayments(data);
      case 'Piastrix': return new Piastrix(data);
      case 'Pin4Pay': return new Pin4Pay(data);
      case 'Plugnpay': return new Plugnpay(data);
      case 'PostFinance': return new PostFinance(data);
      case 'PPRO': return new PPRO(data);
      case 'Prosa': return new Prosa(data);
      case 'PSiGate': return new PSiGate(data);
      case 'Rapyd': return new Rapyd(data);
      case 'Realex': return new Realex(data);
      case 'Realtime': return new Realtime(data);
      case 'Redsys': return new Redsys(data);
      case 'Rotessa': return new Rotessa(data);
      case 'RPN': return new RPN(data);
      case 'Safecharge': return new Safecharge(data);
      case 'Sagepay': return new Sagepay(data);
      case 'SaltarPay': return new SaltarPay(data);
      case 'SeamlessChex': return new SeamlessChex(data);
      case 'SecureTrading': return new SecureTrading(data);
      case 'SecurionPay': return new SecurionPay(data);
      case 'Skrill': return new Skrill(data);
      case 'SmartInvoice': return new SmartInvoice(data);
      case 'SMSVoucher': return new SMSVoucher(data);
      case 'Sofort': return new Sofort(data);
      case 'SparkPay': return new SparkPay(data);
      case 'StaticGateway': return new StaticGateway(data);
      case 'STPMexico': return new STPMexico(data);
      case 'Stripe': return new Stripe(data);
      case 'Tabby': return new Tabby(data);
      case 'Telr': return new Telr(data);
      case 'TestProcessor': return new TestProcessor(data);
      case 'ToditoCash': return new ToditoCash(data);
      case 'Truevo': return new Truevo(data);
      case 'Trustly': return new Trustly(data);
      case 'TrustsPay': return new TrustsPay(data);
      case 'TWINT': return new TWINT(data);
      case 'Unlimit': return new Unlimit(data);
      case 'UPayCard': return new UPayCard(data);
      case 'USAePay': return new USAePay(data);
      case 'VantivLitle': return new VantivLitle(data);
      case 'VCreditos': return new VCreditos(data);
      case 'vegaaH': return new VegaaH(data);
      case 'VegaWallet': return new VegaWallet(data);
      case 'Wallet88': return new Wallet88(data);
      case 'Walpay': return new Walpay(data);
      case 'WesternUnion': return new WesternUnion(data);
      case 'Wirecard': return new Wirecard(data);
      case 'WorldlineAtosFrankfurt': return new WorldlineAtosFrankfurt(data);
      case 'Worldpay': return new Worldpay(data);
      case 'XPay': return new XPay(data);
      case 'Zimpler': return new Zimpler(data);
      case 'Zotapay': return new Zotapay(data);
      default: {
        const error = new Error('Unknown discriminator value');
        error.name = 'UnknownDiscriminatorValue';
        throw error;
      }
    };
  }
}
